### ISSUE TITLE
Cluster tls_context config not sent to Envoy

### ISSUE THREAD

**Issue by tmogstad** [tak2siva/Envoy-Pilot#1]
Hi,

I'm testing Envoy-Pilot as control-plane for envoys using the File Config method.

All looks good except I'm having problems supplying tls_context config through cds. This results in envoys using http to the backend, when I want them to use https.

The same configuration works just fine when configuring envoys statically. 

My CDS.yaml file looks like this:
```
- name: service1
  connect_timeout: 15.0s
  type: STATIC
  dns_lookup_family: V4_ONLY
  lb_policy: ROUND_ROBIN
  hosts: 
  - socket_address: 
      address: 10.10.10.20 
      port_value: 443
  tls_context:
    sni: www.examplehost.com

```
Config_dump from enoy does not include tls_context config.

```{
   "@type": "type.googleapis.com/envoy.admin.v2alpha.ClustersConfigDump",
   "version_info": "bha00nbfmjktkn861csg",
   "static_clusters": [
    {
     "cluster": {
      "name": "xds_cluster",
      "type": "STRICT_DNS",
      "connect_timeout": "0.250s",
      "hosts": [
       {
        "socket_address": {
         "address": "10.10.10.10",
         "port_value": 7777
        }
       }
      ],
      "http2_protocol_options": {},
      "dns_refresh_rate": "5s"
     },
     "last_updated": "2019-02-01T08:16:29.946Z"
    }
   ],
   "dynamic_active_clusters": [
    {
     "version_info": "bha00nbfmjktkn861csg",
     "cluster": {
      "name": "service1",
      "connect_timeout": "15s",
      "hosts": [
       {
        "socket_address": {
         "address": "10.10.10.20",
         "port_value": 443
        }
       }
      ]
     },
     "last_updated": "2019-02-01T08:16:29.953Z"
    }
   ]
  },```

Is what I'm trying to archive possible through cds, or is there something wrong with my syntax in the CDS.yaml file?
